### ISSUE TITLE
Add an option for showing the rotations of party members!

### ISSUE THREAD

**Issue by ArchiDog1998** [ArchiDog1998/ActionTimelineEx#27]
Well, maybe the user is interested in the party member's rotation in runtime.

Is it necessary if someone has ACT?

**Comment by ArchiDog1998** [comment]
Nope, ACT is better.

**Comment by PinkYuDeer** [comment]
Oh, that's a great idea! I need this feature, even in act. But I can't find it, sorry to bother, is this an act plugin or floating window? What's its name?

**Comment by ArchiDog1998** [comment]
I didn't see this feature in Dalamud or ACT.

However, ACT can see all actions **AFTER** the combat. I think that it is enough.
